name: wandroid_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.1
  retrofit: ^1.3.4+1
  pretty_dio_logger: ^1.1.1
  json_annotation: ^3.1.1
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  dio_http_cache: ^0.2.11
  dio_http_formatter: ^1.0.3
  get: ^4.1.4
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.12+4
  webview_flutter: ^2.0.4
  flutter_swiper: ^1.1.6
  fluttertoast: ^8.0.3
  logger: ^0.9.1
  flutter_screenutil: ^5.0.0
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.4.1+3
  build_runner: ^1.11.5
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
